.TH ST 1 st\-VERSION
.SH NAME
st \- simple terminal
.SH SYNOPSIS
.B st
.RB [ \-aiv ]
.RB [ \-c
.IR class ]
.RB [ \-f
.IR font ]
.RB [ \-g
.IR geometry ]
.RB [ \-n
.IR name ]
.RB [ \-o
.IR iofile ]
.RB [ \-T
.IR title ]
.RB [ \-t
.IR title ]
.RB [ \-l
.IR line ]
.RB [ \-w
.IR windowid ]
.RB [[ \-e ]
.IR command
.RI [ arguments ...]]
.PP
.B st
.RB [ \-aiv ]
.RB [ \-c
.IR class ]
.RB [ \-f
.IR font ]
.RB [ \-g
.IR geometry ]
.RB [ \-n
.IR name ]
.RB [ \-o
.IR iofile ]
.RB [ \-T
.IR title ]
.RB [ \-t
.IR title ]
.RB [ \-w
.IR windowid ]
.RB \-l
.IR line
.RI [ stty_args ...]
.SH DESCRIPTION
.B st
is a simple terminal emulator for X which sucks less.

.B wst
basically is the same although it sucks a little more less. But don't
worry: It sucks enough less to be suckless. And it is carefully patched with
some usefull functions and options.

.SH PATCHES

.B \- bold is not bright

In st, bold text is rendered with a bold font in the bright variant of the
current color. This patch makes bold text rendered simply as bold, leaving
the color unaffected.

https://st.suckless.org/patches/bold-is-not-bright/

.B \- clipboard

The Freedesktop standard requires you to remember which clipboard you are
keeping selections in. If you switch between a terminal and browser, you may
find this UX jarring.

Description: This trivial patch sets CLIPBOARD on selection, the same as
your browser. You may want to replace selpaste with clippaste in your
config.h bindings to complete the effect, or develop the habit to delete
config.h before and use config.def.h instead.

https://st.suckless.org/patches/clipboard/

.B \- delkey

Return BS on pressing backspace and DEL on pressing the delete key.

https://st.suckless.org/patches/delkey/

.B \- disable bold/italic fonts globally + disable roman

Some terminals allow disabling bold/italic fonts globally. So this patch
adds such option as well.

Set these options either in config.h, or develop the habit to delete
config.h before compiling and use config.def.h instead:

  int disablebold = 0; # change to 1 to disable bold style
  int disableitalic = 1; # change to 0 to enable italic style
  int disableroman = 0; # ...

Or choose the easy way and define them in .xresources. See below.

.B \- scrollback ringbuffer

Scroll back through terminal output using Shift + {PageUp, PageDown} or if
you don't like to leave home use Alt + {k, j}.

https://st.suckless.org/patches/scrollback/

.B \- w3m

Support w3m images hack. Similar to the patch at the FAQ, but it's simpler,
Same as the FAQ patch, the cursor line is deleted at the image, because st
always renders full lines, even when most of it is empty.

https://st.suckless.org/patches/w3m/

.B \- xresources with signal reloading

This patch adds the ability to configure st via .xresources and signal
reloading. This patch is not based on xresources patch and is extended from
xst's commit on github.

You can basically pass a USR1 signal to all st processes after updating*
your .xresources to reload the settings:

  # pidof st | xargs kill -s USR1

*) A good idea is to load your .xresources before running last mentioned command:

  # xrdb -load .xresources

https://st.suckless.org/patches/xresources-with-reload-signal/

.SH OPTIONS
.TP
.B \-a
disable alternate screens in terminal
.TP
.BI \-c " class"
defines the window class (default $TERM).
.TP
.BI \-f " font"
defines the
.I font
to use when st is run.
.TP
.BI \-g " geometry"
defines the X11 geometry string.
The form is [=][<cols>{xX}<rows>][{+-}<xoffset>{+-}<yoffset>]. See
.BR XParseGeometry (3)
for further details.
.TP
.B \-i
will fixate the position given with the -g option.
.TP
.BI \-n " name"
defines the window instance name (default $TERM).
.TP
.BI \-o " iofile"
writes all the I/O to
.I iofile.
This feature is useful when recording st sessions. A value of "-" means
standard output.
.TP
.BI \-T " title"
defines the window title (default 'st').
.TP
.BI \-t " title"
defines the window title (default 'st').
.TP
.BI \-w " windowid"
embeds st within the window identified by
.I windowid
.TP
.BI \-l " line"
use a tty
.I line
instead of a pseudo terminal.
.I line
should be a (pseudo-)serial device (e.g. /dev/ttyS0 on Linux for serial port
0).
When this flag is given
remaining arguments are used as flags for
.BR stty(1).
By default st initializes the serial line to 8 bits, no parity, 1 stop bit
and a 38400 baud rate. The speed is set by appending it as last argument
(e.g. 'st -l /dev/ttyS0 115200'). Arguments before the last one are
.BR stty(1)
flags. If you want to set odd parity on 115200 baud use for example 'st -l
/dev/ttyS0 parenb parodd 115200'. Set the number of bits by using for
example 'st -l /dev/ttyS0 cs7 115200'. See
.BR stty(1)
for more arguments and cases.
.TP
.B \-v
prints version information to stderr, then exits.
.TP
.BI \-e " command " [ " arguments " "... ]"
st executes
.I command
instead of the shell.  If this is used it
.B must be the last option
on the command line, as in xterm / rxvt.
This option is only intended for compatibility,
and all the remaining arguments are used as a command
even without it.
.SH SHORTCUTS
.TP
.B Break
Send a break in the serial line.
Break key is obtained in PC keyboards
pressing at the same time control and pause.
.TP
.B Ctrl-Print Screen
Toggle if st should print to the
.I iofile.
.TP
.B Shift-Print Screen
Print the full screen to the
.I iofile.
.TP
.B Print Screen
Print the selection to the
.I iofile.
.TP
.B Alt-Shift-K / Ctrl-Shift-Page Up
Increase font size.
.TP
.B Alt-Shift-J / Ctrl-Shift-Page Down
Decrease font size.
.TP
.B Alt-Shift-H / Ctrl-Shift-Home
Reset to default font size.
.TP
.B Ctrl-Shift-y
Paste from primary selection (middle mouse button).
.TP
.B Ctrl-Shift-c
Copy the selected text to the clipboard selection.
.TP
.B Ctrl-Shift-v
Paste from the clipboard selection.
.TP
.B Alt-k
Scroll up
.TP
.B Alt-j
Scroll down
Paste from the clipboard selection.
.SH CUSTOMIZATION
.B st
can be customized by creating a custom config.h and (re)compiling the source
code. This keeps it fast, secure and simple.
.SH AUTHORS
See the LICENSE file for the authors.
.SH LICENSE
See the LICENSE file for the terms of redistribution.
.SH SEE ALSO
.BR tabbed (1),
.BR utmp (1),
.BR stty (1),
.BR scroll (1),
.BR kitty (1)
.SH BUGS
See the TODO file in the distribution.
.SH Good luck!

  Wako Diwe <wako.diwe@gmail.com>
  wst: https://github.com/wakodiwe/wst
